Description: This template is to build the webserver for usermanagement

Parameters:
  Stage:
    Description: The environment to which this will be deployed
    Type: String
    Default: dev
  InstanceType:
    Description: The AWS Type of the webserver
    Type: String
    Default: t2.micro

  KeyName:
    Description: Name of AWS key to use
    Type: String
    Default: user-management-key

Resources:
  WebServerNode1:
    Type: AWS::EC2::Instance
    Properties:
        InstanceType: !Ref InstanceType
        ImageId: ami-0b898040803850657
        KeyName: !Ref KeyName
        IamInstanceProfile: !ImportValue user-management-security-WebEC2InstanceProfile
        UserData: 
            Fn::Base64: 
             
             !Sub |
                #!/bin/bash             
                    yum update -y
                    yum install -y tomcat
                    yum install -y tomcat-webapps
                    yum install -y tomcat-admin-webapps
                    echo Stack="${AWS::StackName}" >> /usr/share/tomcat/conf/tomcat.conf
                    echo Stage="${Stage}" >> /usr/share/tomcat/conf/tomcat.conf
                    aws s3api get-object --bucket tomcat-config-td --key tomcat-users.xml /usr/share/tomcat/conf/tomcat-users.xml
                    service tomcat start
                    systemctl enable tomcat.service
                    yum install -y ruby
                    aws s3 cp s3://aws-codedeploy-us-east-1/latest/install . --region us-east-1
                    chmod +x ./install
                    ./install auto

        SecurityGroupIds:
          - !ImportValue user-management-security-WebServerSecurityGroupId
        SubnetId: !ImportValue user-management-vpc-PublicSubnet1
        Tags: 
          - 
            Key: "Name"
            Value: !Join [ "-", [user-management-web, !Ref Stage ]]
Outputs:
  WebServerURL:
    Description: "URL to access our Tomcat Server"
    Value: !Join
    - ''
    - - 'http://'
      - !GetAtt WebServerNode1.PublicIp
      - ':8080'
    Export:
      Name: !Sub "${AWS::StackName}-TomcatURL"